---
- name: Install packages
  become: true
  ansible.builtin.apt:
    name:
      - rustup
      - build-essential
    state: present
    update_cache: true

- name: Put cargo in PATH
  become: true
  ansible.builtin.copy:
    src: assets/cargo-path.sh
    dest: /etc/profile.d/cargo-path.sh

- name: Set default Rust version
  ansible.builtin.command: rustup default stable
