---
- name: Install Rustup
  ansible.builtin.include_tasks: winget.yml
  vars:
    id: Rustlang.Rustup
  # Microsoft.VCLibs.Desktop.14
  # Microsoft.VCRedist.2005.x86
  # Microsoft.VCRedist.2015+.x64
  # Microsoft.VCRedist.2015+.x86
  # Microsoft.VisualStudio.2022.BuildTools

- name: Update Visual Studio modules
  ansible.windows.win_dsc:
    resource_name: Microsoft.VisualStudio.DSC/VSComponents
    ProductId: Microsoft.VisualStudio.Product.BuildTools
    ChannelId: VisualStudio.17.Release
    Components:
      - Microsoft.VisualStudio.Workload.VCTools
      - Microsoft.VisualStudio.Component.VC.Tools.x86.x64
      - Microsoft.VisualStudio.Component.Windows11SDK.22621

- name: Find Visual Studio tools 
  register: vs_tools_results
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding(SupportsShouldProcess)]
      param ()

      $msvcBase = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC"
      $latestVersion = Get-ChildItem -Path $msvcBase | Sort-Object Name -Descending | Select-Object -First 1
      $msvcBinPath = Join-Path -Path $latestVersion.FullName -ChildPath "bin\HostX64\x64"
      $llvmBinPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\BuildTools\VC\Tools\Llvm\bin"

      $Ansible.Changed = $false
      $Ansible.Result = [PSCustomObject]@{
        msvc_path = $msvcBinPath
        llvm_path = $llvmBinPath
      }

- name: Put Visual Studio tools in PATH
  ansible.windows.win_path:
    elements:
      - vs_tools_results.result.msvc_path
      - vs_tools_results.result.llvm_path

- name: Install Rust version 1.74.0
  ansible.windows.win_command: rustup toolchain install 1.74.0
  register: rustup_old
  changed_when: "' unchanged ' not in rustup_old.stdout"

- name: Set default Rust version
  ansible.windows.win_command: rustup default stable
  register: rustup_default
  changed_when: "' unchanged ' not in rustup_default.stdout"

- name: Add rust-analyzer for Rust version 1.74.0
  ansible.windows.win_command: rustup +1.74.0 component add rust-analyzer
  register: rust_analyzer_old
  changed_when: "'is up to date' not in rust_analyzer_old.stdout"

- name: Add rust-analyzer for stable Rust
  ansible.windows.win_command: rustup component add rust-analyzer
  register: rust_analyzer
  changed_when: "'is up to date' not in rust_analyzer.stdout"

- name: Remove Zig compiler
  ansible.windows.win_package:
    product_id: zig.zig
    state: absent
