---
- name: System
  hosts: all
  vars_files:
    - secrets.yml
  roles:
    - network

- name: Workstation
  hosts: workstation
  vars_files:
    - secrets.yml
  roles:
    - desktop

- name: Containerization platform
  hosts: kube:worker
  vars_files:
    - secrets.yml
  roles:
    - platform

- name: Development Environment
  hosts: development
  vars_files:
    - secrets.yml
  roles:
    - docker
    - lazyvim

- name: Proxmox Host
  hosts: proxmox
  vars_files:
    - secrets.yml
  roles:
    - proxmox

