---
- name: System
  hosts: all
  vars_files:
    - secrets.yml
  roles:
    - network
    - ssh-client
    - ssh-server

- name: Workstation
  hosts: workstation
  vars_files:
    - secrets.yml
  roles:
    - comms
    - office
    - media
    - protect
    - trusted
    - docker

- name: Yubikey station
  hosts: yubikey
  vars_files:
    - secrets.yml
  roles:
    - yubikey

- name: Kubernetes
  hosts: kube:worker
  vars_files:
    - secrets.yml
  roles:
    - kubernetes

- name: Development Environment
  hosts: development
  vars_files:
    - secrets.yml
  roles:
    - docker
    - lazyvim
    - oh-my-posh

- name: Content Creation
  hosts: cougar
  vars_files:
    - secrets.yml
  roles:
    - illustration

- name: Proxmox Host
  hosts: proxmox
  vars_files:
    - secrets.yml
  roles:
    - proxmox

- name: Artificial Intelligence
  hosts: cougar-wsl
  vars_files:
    - secrets.yml
  roles:
    - ai

- name: Internet of Things
  hosts: kentucky-iot
  vars_files:
    - secrets.yml
  roles:
    - iot-gateway
