---
- name: System
  hosts: all
  vars_files:
    - secrets.yml
  roles:
    - network

- name: Workstation
  hosts: workstation
  vars_files:
    - secrets.yml
  roles:
    - comms
    - nerdfont
    - trusted
    - virtualization

- name: Virtualization
  hosts: kube:worker
  vars_files:
    - secrets.yml
  roles:
    - virtualization

- name: Development Environment
  hosts: development
  vars_files:
    - secrets.yml
  roles:
    - virtualization
    - lazyvim

- name: Proxmox Host
  hosts: proxmox
  vars_files:
    - secrets.yml
  roles:
    - proxmox

