---
- name: System
  hosts: all
  vars_files:
    - secrets.yml
  roles:
    - network

- name: Workstation
  hosts: workstation
  vars_files:
    - secrets.yml
  roles:
    - desktop

- name: Development Environment
  hosts: development
  vars_files:
    - secrets.yml
  roles:
    - lazyvim
