---
- name: System
  hosts: all
  vars_files:
    - secrets.yml
  roles:
    - network
    - ssh

- name: Workstation
  hosts: workstation
  vars_files:
    - secrets.yml
  roles:
    - comms
    - docs
    - trusted
    - virtualization

- name: Virtualization
  hosts: kube:worker
  vars_files:
    - secrets.yml
  roles:
    - virtualization

- name: Development Environment
  hosts: development
  vars_files:
    - secrets.yml
  roles:
    - virtualization
    - lazyvim
    - oh-my-posh

- name: Proxmox Host
  hosts: proxmox
  vars_files:
    - secrets.yml
  roles:
    - proxmox

