---
collections:
  - name: ansible.windows
    source: https://galaxy.ansible.com
  - name: community.docker
    version: ">=3.9.0"
    source: https://galaxy.ansible.com
  - name: community.windows
    source: https://galaxy.ansible.com
