---
- name: Manage LazyGit (Debian-like)
  when: ansible_os_family == "Debian"
  ansible.builtin.include_tasks: debian.yml
  vars:
    lazygit_config_dir: "{{ ansible_user_dir }}/.config/git"

- name: Manage LazyGit (Windows)
  when: ansible_system == "Windows"
  ansible.builtin.include_tasks: windows.yml
  vars:
    lazygit_config_dir: "{{ lookup('env', 'LOCALAPPDATA') }}\\lazygit"

