---
- name: Install LazyGit
  ansible.builtin.include_tasks: winget.yml
  vars:
    id: JesseDuffield.lazygit

- name: Ensure config directory exists
  ansible.windows.win_file:
    path: "{{ lazygit_config_dir }}"
    state: directory

- name: Copy lazygit config file
  ansible.windows.win_copy:
    src: "assets/lazygit.yml"
    dest: "{{ lazygit_config_dir }}\\config.yml"

