---
- name: Manage NerdFont (Linux)
  when: ansible_system == "Linux" and ansible_virtualization_type != "wsl"
  ansible.builtin.include_tasks: linux.yml

- name: Manage NerdFont (Windows)
  when: ansible_system == "Windows"
  ansible.builtin.include_tasks: windows.yml
