---
- name: Install NerdFont (Linux w/o WSL)
  become: true
  when: ansible_system == "Linux" and ansible_virtualization_type != "wsl"
  block:
    - name: Ensure font directory exists
      ansible.builtin.file:
        path: /usr/share/fonts/truetype/nerdfont
        state: directory

    - name: Install 0xProto
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/0xProto.tar.xz
        include:
          - 0xProtoNerdFontMono-Italic.ttf
          - 0xProtoNerdFont-Bold.ttf
          - 0xProtoNerdFontMono-Regular.ttf
          - 0xProtoNerdFont-Italic.ttf
          - 0xProtoNerdFontPropo-Bold.ttf
          - 0xProtoNerdFont-Regular.ttf
          - 0xProtoNerdFontPropo-Italic.ttf
          - 0xProtoNerdFontMono-Bold.ttf
          - 0xProtoNerdFontPropo-Regular.ttf
        dest: "/usr/share/fonts/truetype/nerdfont/"
        remote_src: yes

- name: Install 0xProto NerdFont (Windows)
  ansible.windows.win_powershell:
    parameters:
      FontName: 0xProto
      Present: true
    script: |
      [CmdletBinding(SupportsShouldProcess)]
      param (
        [String]
        $FontName,

        [Switch]
        $Present
      )

      # Check if the font is installed
      Add-Type -AssemblyName System.Drawing
      $fonts = (New-Object System.Drawing.Text.InstalledFontCollection).Families
      $fontExists = $fonts | Where-Object { $_.Name -eq $fontName }

      if (-not $fontExists -and $Present) {
        try {
          $null = Get-InstalledModule -Name NerdFonts -ErrorAction Stop
        } catch {
          if ($PSCmdlet.ShouldProcess('target')) {
            Install-Module -Name NerdFonts -Repository PSGallery -Force -Scope AllUsers
          }
        }

        if ($PSCmdlet.ShouldProcess('target')) {
          Import-Module NerdFonts
          $baseFontName = $FontName -replace '\s+Nerd\s+Font$', ''
          Install-NerdFont -Name $baseFontName -Scope AllUsers
        }
      } elseif ($fontExists -and -not $Present) {
        if ($PSCmdlet.ShouldProcess('target')) {
          Uninstall-Font -Name $FontName
        }
      } else {
        $Ansible.Changed = $false
      }
