---
- name: Manage Node (Linux)
  when: ansible_system == "Linux"
  ansible.builtin.include_tasks: linux.yml

- name: Manage Node (Windows)
  when: ansible_system == "Windows"
  ansible.builtin.include_tasks: windows.yml
