---
- name: Enable mirrored networking for WSL
  community.general.ini_file:
    path: "{{ ansible_user_dir }}\\.wslconfig"
    section: wsl2
    option: networkingMode
    value: mirrored

- name: Configure WSL host address loopback
  community.general.ini_file:
    path: "{{ ansible_user_dir }}\\.wslconfig"
    section: experimental
    option: hostAddressLoopback
    value: true

- name: Configure WSL swap disabled
  community.general.ini_file:
    path: "{{ ansible_user_dir }}\\.wslconfig"
    section: wsl2
    option: swap
    value: 0

- name: Allow WSL input connections
  ansible.windows.win_shell: >
    Set-NetFirewallHyperVVMSetting
    -Name '{40E0AC32-46A5-438A-A0B2-2B479E8F2E90}'
    -DefaultInboundAction Allow

- name: Install Windows features
  register: install_windows_feature_result
  ansible.windows.win_feature:
    name:
      - Containers
      - Hyper-V
      - Hyper-V-PowerShell
    state: present

- name: Enable Windows optional features.
  register: enable_optional_feature_result
  ansible.windows.win_optional_feature:
    name:
      - Containers
      - Microsoft-Hyper-V
      - Microsoft-Windows-Subsystem-Linux
      - VirtualMachinePlatform
    state: present
    include_parent: true

- name: Disable Windows optional features.
  register: disable_optional_feature_result
  ansible.windows.win_optional_feature:
    name:
      - Microsoft-Hyper-V-Online
    state: absent
    include_parent: true

- name: Activate features with reboot
  ansible.windows.win_reboot:
  when: >
    (install_windows_feature_result.results | selectattr('reboot_required') | map(attribute='reboot_required') | list | length > 0) or
    (enable_optional_feature_result.results | selectattr('reboot_required') | map(attribute='reboot_required') | list | length > 0) or
    (disable_optional_feature_result.results | selectattr('reboot_required') | map(attribute='reboot_required') | list | length > 0)

- name: "Install Ubuntu 24.04"
  ansible.builtin.include_tasks: winget.yml
  vars:
    id: Canonical.Ubuntu.2404
