---
- name: Manage SSH (Debian-like)
  when: ansible_os_family == "Debian"
  ansible.builtin.include_tasks: debian.yml
  vars:
    ssh_config_dir: "{{ ansible_user_dir }}/.ssh"

- name: Manage SSH (Windows)
  when: ansible_system == "Windows"
  ansible.builtin.include_tasks: windows.yml
  vars:
    sshd_config_dir: "{{ lookup('env', 'PROGRAMDATA') }}\\ssh"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
