---
- name: Fail if OS family is unsupported
  when: ansible_os_family != "Debian"
  ansible.builtin.fail:
    msg: "Update the playbook to support the ansible_os_family=={{ ansible_os_family }}"

- name: Install socat
  become: true
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name:
      - socat
    state: present
    update_cache: true

- name: Install ssh agent proxy
  ansible.builtin.copy:
    src: assets/wsl-ssh-agent.sh
    dest: /etc/profile.d/wsl-ssh-agent.sh

- name: Configure SSHd to use alternate port
  become: true
  ansible.builtin.copy:
    src: "assets/sshd_config.alternate_port"
    dest: "/etc/ssh/sshd_config.d/alternate_port.conf"

