---
- name: Manage networking (WSL)
  when: ansible_virtualization_type == "wsl"
  ansible.builtin.include_tasks: wsl.yml

- name: Manage networking (Windows)
  when: ansible_system == "Windows"
  ansible.builtin.include_tasks: windows.yml
