---
- name: Manage Git (Debian-like)
  when: ansible_os_family == "Debian"
  ansible.builtin.include_tasks: debian.yml
  vars:
    git_config_dir: "{{ ansible_user_dir }}/.config/git"

- name: Manage Git (Windows)
  when: ansible_system == "Windows"
  ansible.builtin.include_tasks: windows.yml
  vars:
    # Valid since 2.46.0: https://github.com/git-for-windows/git/discussions/5097
    git_config_dir: "{{ lookup('env', 'LOCALAPPDATA') }}\\Git"
