---
- name: Install LazyVim dependencies
  become: true
  ansible.builtin.apt:
    name:
      - ripgrep
      - fzf
    state: present
    update_cache: true

- name: Clone LazyVim configuration
  ansible.builtin.git:
    repo: https://github.com/FlippingBinary/nvim-config.git
    dest: "{{ ansible_user_dir + '/.config/nvim' }}"
    clone: true
    force: true
