---
- name: Install LazyVim dependencies
  become: true
  ansible.builtin.apt:
    name:
      - fzf
      - imagemagick
      - python3-pip
      - python3-venv
      - ripgrep
      - unzip
    state: present

- name: Clone LazyVim configuration
  ansible.builtin.git:
    repo: https://github.com/FlippingBinary/nvim-config.git
    dest: "{{ ansible_user_dir + '/.config/nvim' }}"
    clone: true
    force: true
