---
- name: Manage LazyVim (Debian-like)
  when: ansible_os_family == "Debian"
  ansible.builtin.include_tasks: debian.yml

- name: Manage LazyVim (Windows)
  when: ansible_system == "Windows"
  ansible.builtin.include_tasks: windows.yml

- name: Install tree-sitter CLI
  community.general.cargo:
    name: tree-sitter-cli

- name: Install fd-find with Cargo
  community.general.cargo:
    name: fd-find
