---
- name: "Install {{ item }}"
  ansible.builtin.include_tasks: winget.yml
  vars:
    id: "{{ item }}"
  loop:
    - Microsoft.PowerShell
    - Microsoft.WindowsTerminal
    - 7zip.7zip
    - AstroComma.AstroGrep
    - BurntSushi.ripgrep.MSVC
    - junegunn.fzf
    - ImageMagick.ImageMagick
    - Python.Python.3.12

- name: Clone LazyVim configuration
  ansible.windows.win_powershell:
    parameters:
      Repository: https://github.com/FlippingBinary/nvim-config.git
      Destination: "{{ lookup('env', 'LOCALAPPDATA') }}/nvim"
    script: |
      [CmdletBinding(SupportsShouldProcess)]
      param (
        [String]
        $Repository,

        [String]
        $Destination
      )

      # Check if the folder exists
      if ((Get-Item $Destination).PSIsContainer -eq $true) {
        $Ansible.changed = $false
      } elseif ($PSCmdlet.ShouldProcess('target')) {
        git clone $Repository $Destination
      }
