---
- name: Run Z-Wave JS UI in Docker
  community.docker.docker_compose_v2:
    project_name: zwave-js-ui
    definition:
      services:
        watchtower:
          image: containrrr/watchtower
          pull_policy: always
          container_name: watchtower
          environment:
            TZ: America/New_York
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
          command: --cleanup --remove-volumes --schedule "0 0 3 * * *"
          restart: unless-stopped

        zwave-js-ui:
          container_name: zwave-js-ui
          image: zwavejs/zwave-js-ui:latest
          pull_policy: always
          restart: always
          tty: true
          stop_signal: SIGINT
          environment:
            SESSION_SECRET: "{{ zwave_session }}"
            ZWAVEJS_EXTERNAL_CONFIG: /usr/src/app/store/.config-db
            TZ: America/New_York
          devices:
            - '/dev/serial/by-id/{{ zwave_device }}:/dev/zwave'
          volumes:
            - /opt/zwave-js-ui:/usr/src/app/store
          ports:
            - '8091:8091' # port for web interface
            - '3000:3000' # port for Z-Wave JS websocket server
