---
- name: Remove conflicting packages
  become: true
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent

- name: Enable IP forwarding
  become: true
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: net.ipv4.ip_forward = 1

- name: Install required system packages
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-apt
    state: present
    update_cache: true

- name: Get Docker GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: u+rw,g+r,o+r

- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: >
      deb
      [arch={{ arch_map[ansible_architecture] | default(ansible_architecture) }}
      signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }}
      stable
    state: present
  vars:
    arch_map:
      x86_64: amd64
      aarch64: arm64
      armv6l: armel
      armv7l: armhf
      i386: i386
      i686: i386
      ppc: powerpc

- name: Install Docker packages
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
    state: present

- name: Get NVIDIA Container Toolkit GPG key
  become: true
  when: nvidia_container_toolkit
  register: gpg_key_download
  ansible.builtin.get_url:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    dest: /etc/apt/keyrings/nvidia-container-toolkit-keyring.asc
    mode: u+rw,g+r,o+r

- name: Add NVIDIA Container Toolkit repository
  become: true
  when: nvidia_container_toolkit
  ansible.builtin.apt_repository:
    repo: >
      deb
      [arch={{ arch_map[ansible_architecture] | default(ansible_architecture) }}
      signed-by=/etc/apt/keyrings/nvidia-container-toolkit-keyring.asc]
      https://nvidia.github.io/libnvidia-container/stable/deb/{{ arch_map[ansible_architecture] | default(ansible_architecture) }}
      /
    state: present
  vars:
    arch_map:
      x86_64: amd64
      aarch64: arm64
      armv6l: armel
      armv7l: armhf
      i386: i386
      i686: i386
      ppc: powerpc

- name: Install NVIDIA Container Toolkit
  become: true
  when: nvidia_container_toolkit
  ansible.builtin.apt:
    name:
      - nvidia-container-toolkit
    update_cache: true
    state: present

- name: Add Ansible user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  notify:
    - Reconnect to finalize group membership

- name: Manage docker service
  become: true
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

- name: Manage containerd service
  become: true
  ansible.builtin.service:
    name: containerd
    enabled: true
    state: started

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
