---
- name: Remove conflicting packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent

- name: Install required system packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-apt
    state: present
    update_cache: true

- name: Get Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: u+rw,g+r,o+r

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >
      deb
      [arch={{ arch_map[ansible_architecture] | default(ansible_architecture) }}
      signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/debian
      {{ ansible_distribution_release }}
      stable
    state: present
  vars:
    arch_map:
      x86_64: amd64
      aarch64: arm64
      armv6l: armel
      armv7l: armhf
      i386: i386
      i686: i386
      ppc: powerpc

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
    state: present

- name: Add Ansible user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  notify:
    - Reconnect to finalize group membership

- name: Manage docker service
  ansible.builtin.service:
    name:
      - docker
      - containerd
    enabled: true
    state: started

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
