---
- name: Manage Docker (Debian-like)
  when: ansible_os_family == "Debian"
  become: true
  ansible.builtin.include_tasks: debian.yml

- name: Manage Docker (Windows)
  when: ansible_system == "Windows"
  ansible.builtin.include_tasks: windows.yml
