---
- name: Manage containerd (Debian-like)
  when: ansible_os_family == "Debian"
  ansible.builtin.include_tasks: debian.yml

- name: Manage containerd (Windows)
  when: ansible_system == "Windows"
  ansible.builtin.include_tasks: windows.yml
  vars:
    containerd_path: "{{ lookup('env','PROGRAMFILES') }}\\containerd"
