---
- name: Install Bob for NeoVim
  community.general.cargo:
    name: bob-nvim

- name: Install Bob PATH (Debian-like)
# NOTE: The Windows version installs the PATH, but not the Linux version apparently
  become: true
  when: ansible_os_family == "Debian"
  ansible.builtin.copy:
    src: assets/bob-path.sh
    dest: /etc/profile.d/bob-path.sh

- name: Remove system-wide NeoVim
  when: ansible_platform == "Windows"
  ansible.windows.win_package:
    product_id: Neovim.Neovim
    state: absent
